/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "adc.h"
#include "i2c.h"
#include "i2c_lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
    int ret;
    uint16_t val;
    char str[32];  // String to store ADC value
    SystemInit();  // Initialize system

    // Initialize ADC and LCD
    ADC_Init();
    ret = Lcd_Init();

    // Check if LCD initialization was successful
    if(ret) {
        while(1) {
            // Read the ADC value
            val = ADC_GetValue();

            // Convert the ADC value to a string for display
            sprintf(str, "ADC = %u", val);

            // Display the ADC value on the LCD (assuming line1 is defined)
            Lcd_Puts(LCD_LINE1, str);

            // Delay for a second before updating the display again
            DelayMs(1000);
        }
    }

    return 0;
}

